apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "simple-webapp.fullname" . }}-pdb
  labels:
    {{- include "simple-webapp.labels" . | nindent 4 }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- else if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "simple-webapp.selectorLabels" . | nindent 6 }}